id: I59704000
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T23:19:33+00:00'
last_modified: '2022-06-07T12:26:31.135549+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W20127
  title: རྩོམ་དཔྱད་གཏམ་ཚོགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    CE6B:
      image_group_id: I1KG21098
      title: ''
      total_pages: 530
      order: 1
      base_file: CE6B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
