id: P000608
initial_creation_type: ocr
source_metadata:
  id: bdr:W20127
  title: རྩོམ་དཔྱད་གཏམ་ཚོགས།
  author: ''
  volumes:
    621eb624a30647e58a4e6191c7a9ba82:
      image_group_id: I1KG21098
      title: ''
      volume_number: 1
      total_pages: 530
