id: P000608
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-16 15:50:56.750637
source_metadata:
  id: bdr:W20127
  title: རྩོམ་དཔྱད་གཏམ་ཚོགས།
  author: ''
  volumes:
    621eb624a30647e58a4e6191c7a9ba82:
      image_group_id: I1KG21098
      title: ''
      volume_number: 1
      total_pages: 530
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
